// File generated by FlutterFire CLI.
// Run `flutterfire configure` to regenerate this file with your Firebase project settings.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux. '
          'You can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP1AStvMrRMFHLWEcOC_gsjcFw8xQJ_u8',
    appId: '1:151949139234:web:58aa3ee81722541738d97b',
    messagingSenderId: '151949139234',
    projectId: 'gazuproyecto',
    authDomain: 'gazuproyecto.firebaseapp.com',
    storageBucket: 'gazuproyecto.firebasestorage.app',
    measurementId: 'G-X2K49BDYJE',
  );

  // ---------------------------------------------------------------------------
  // TODO: Replace placeholder values below with your platform-specific configs.
  // Run `flutterfire configure` in the project root to generate them
  // automatically, or copy the values from google-services.json / GoogleService-Info.plist.
  // ---------------------------------------------------------------------------

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: 'YOUR_ANDROID_APP_ID',
    messagingSenderId: '151949139234',
    projectId: 'gazuproyecto',
    storageBucket: 'gazuproyecto.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: '151949139234',
    projectId: 'gazuproyecto',
    storageBucket: 'gazuproyecto.firebasestorage.app',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'com.example.gazu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: '151949139234',
    projectId: 'gazuproyecto',
    storageBucket: 'gazuproyecto.firebasestorage.app',
    iosClientId: 'YOUR_MACOS_CLIENT_ID',
    iosBundleId: 'com.example.gazu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP1AStvMrRMFHLWEcOC_gsjcFw8xQJ_u8',
    appId: 'YOUR_WINDOWS_APP_ID',
    messagingSenderId: '151949139234',
    projectId: 'gazuproyecto',
    authDomain: 'gazuproyecto.firebaseapp.com',
    storageBucket: 'gazuproyecto.firebasestorage.app',
  );
}
